version: 2

project_name: proj

before:
  hooks:
    - go mod download

builds:
  - binary: proj
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - format: zip
    only:
      - darwin
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - format: tar.gz
    only:
      - linux
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

nfpms:
  - package_name: proj
    homepage: https://github.com/cutehax0r/proj
    maintainer: "cutehax0r <97819453+cutehax0r@users.noreply.github.com>"
    description: "A tool for setting up new projects or adding files to existing projects"
    license: MIT
    formats:
      - deb
      - rpm
    architectures:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: cutehax0r
    repo: proj

changelog:
  sort: asc
  use: github-native
