version: 2

project_name: proj

before:
  hooks:
    - go mod download
    - go install github.com/cpuguy83/go-md2man/v2@latest
    - make man

builds:
  - binary: proj
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - formats: [zip]
    format_overrides:
      - goos: linux
        formats: [tar.gz]
    files:
      - src: bin/man/*
        dst: man

nfpms:
  - package_name: proj
    homepage: https://github.com/cutehax0r/proj
    maintainer: "cutehax0r <97819453+cutehax0r@users.noreply.github.com>"
    description: "A tool for setting up new projects or adding files to existing projects"
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    contents:
      - src: bin/man/proj.1
        dst: /usr/share/man/man1/proj.1
      - src: bin/man/proj-new.1
        dst: /usr/share/man/man1/proj-new.1
      - src: bin/man/proj-add.1
        dst: /usr/share/man/man1/proj-add.1
      - src: bin/man/proj-help.1
        dst: /usr/share/man/man1/proj-help.1
      - src: bin/man/proj.yml.5
        dst: /usr/share/man/man5/proj.yml.5
      - src: bin/man/proj.7
        dst: /usr/share/man/man7/proj.7
      - src: bin/man/proj-scripts.7
        dst: /usr/share/man/man7/proj-scripts.7
      - src: bin/man/proj-lua.7
        dst: /usr/share/man/man7/proj-lua.7
      - src: bin/man/proj-variables.7
        dst: /usr/share/man/man7/proj-variables.7
      - src: bin/man/proj-template.7
        dst: /usr/share/man/man7/proj-template.7

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  draft: false
  prerelease: false

changelog:
  sort: asc
  use: github-native
