version: 2

project_name: proj

before:
  hooks:
    - go mod download

builds:
  - binary: proj
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - id: macos
    format: zip
    goos:
      - darwin
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - id: linux
    format: tar.gz
    goos:
      - linux
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

nfpms:
  - id: deb
    package_name: proj
    homepage: https://github.com/cutehax0r/proj
    maintainer: "cutehax0r <97819453+cutehax0r@users.noreply.github.com>"
    description: "A tool for setting up new projects or adding files to existing projects"
    license: MIT
    formats:
      - deb
    contents:
      - src: proj
        dst: /usr/local/bin/proj

  - id: rpm
    package_name: proj
    homepage: https://github.com/cutehax0r/proj
    maintainer: "cutehax0r <97819453+cutehax0r@users.noreply.github.com>"
    description: "A tool for setting up new projects or adding files to existing projects"
    license: MIT
    formats:
      - rpm
    contents:
      - src: proj
        dst: /usr/local/bin/proj

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: cutehax0r
    repo: proj

changelog:
  sort: asc
  use: github-native
