---
# Example configuration file. By default this should be
# in ~/.config/proj/config.yml

# This is the path to locate the project templates. See the example template for details of their
templates_path: ~/.local/share/proj

# By default create projects in this path. If not set then $CWD will be used.
default_path: ~/Documents/src/github.com/cutehax0r

# How noisey should logs be. You probably only want `Error` unless you're debugging
log_level: Debug

# Specify global before/after scripts. These run for all projects
scripts:
  # before: nil # if set this script runs before the project level 'before.lua'
  # after: nil # if set this script runs after the project level 'after.lua'

# These variables are available inside of lua scripts and templates.
# Right now, owing to laziness they're passed around as a map[string]string but eventually I'll
# write a nice recursive 'transformer' to make these go to sane primitive types in lua.
variables:
  email: cutehaxOr@example.com
  user: cute haxor
  port: 42069
  cute: true
